# Generated by Django 4.0.3 on 2022-04-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='Tour',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Tour',
            new_name='tour',
        ),
    ]
